---
- name: remove apapche and firewall rule
  hosts: ansible1
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: remove apache
      yum:
        name: httpd
        state: absent
    - name: remove FW rule
      firewalld:
        immediate: true
        state: disabled