---
- name: install mariadb and python2-PyMySQL
  hosts: all
  remote_user: ansible
  become_method: sudo
  become: yes
  become_user: root
  tasks:
    - name: set mariadb
      block:
      - name: install mariadb
        yum:
          name:
            - mariadb-server
            - python2-PyMySQL
          state: present
      - name: enable mariadb
        service:
          name: mariadb
          state: started
          enabled: yes
        notify:
          - set db pass
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version == "7"
  handlers:
    - name: set db pass
      mysql_user:
        name: root
        password: password