---
- name: Add local facts
  hosts: all
  remote_user: ansible
  become_method: sudo
  become: yes
  become_user: root
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: localfacts.fact
  tasks:
    - name: create fact directory
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    - name: copy facts file
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"

- name: install package from local facts
  hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: install package
      yum:
        name: "{{ ansible_local.localfacts.localfacts.package }}"
        state: present
    - name: start and enable
      service:
        name: "{{ ansible_local.localfacts.localfacts.package }}"
        state: started
        enabled: yes
